<?php

namespace Container9HJjwqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Av4G21Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.av4_g21' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.av4_g21'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'group' => ['privates', '.errored..service_locator.av4_g21.App\\Entity\\Group', NULL, 'Cannot autowire service ".service_locator.av4_g21": it needs an instance of "App\\Entity\\Group" but this type has been excluded in "config/services.yaml".'],
        ], [
            'group' => 'App\\Entity\\Group',
        ]);
    }
}
