<?php

namespace Container9HJjwqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_48C_Ew9Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.48C.ew9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.48C.ew9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AcceptGroupRequestController::__invoke' => ['privates', '.service_locator.HWySRUk', 'get_ServiceLocator_HWySRUkService', true],
            'App\\Controller\\GetMembers::__invoke' => ['privates', '.service_locator.av4_g21', 'get_ServiceLocator_Av4G21Service', true],
            'App\\Controller\\GetThreadController::__invoke' => ['privates', '.service_locator.WQp8s5H', 'get_ServiceLocator_WQp8s5HService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AcceptGroupRequestController:__invoke' => ['privates', '.service_locator.HWySRUk', 'get_ServiceLocator_HWySRUkService', true],
            'App\\Controller\\AcceptGroupRequestController' => ['privates', '.service_locator.HWySRUk', 'get_ServiceLocator_HWySRUkService', true],
            'App\\Controller\\GetMembers:__invoke' => ['privates', '.service_locator.av4_g21', 'get_ServiceLocator_Av4G21Service', true],
            'App\\Controller\\GetMembers' => ['privates', '.service_locator.av4_g21', 'get_ServiceLocator_Av4G21Service', true],
            'App\\Controller\\GetThreadController:__invoke' => ['privates', '.service_locator.WQp8s5H', 'get_ServiceLocator_WQp8s5HService', true],
            'App\\Controller\\GetThreadController' => ['privates', '.service_locator.WQp8s5H', 'get_ServiceLocator_WQp8s5HService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AcceptGroupRequestController::__invoke' => '?',
            'App\\Controller\\GetMembers::__invoke' => '?',
            'App\\Controller\\GetThreadController::__invoke' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AcceptGroupRequestController:__invoke' => '?',
            'App\\Controller\\AcceptGroupRequestController' => '?',
            'App\\Controller\\GetMembers:__invoke' => '?',
            'App\\Controller\\GetMembers' => '?',
            'App\\Controller\\GetThreadController:__invoke' => '?',
            'App\\Controller\\GetThreadController' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
