<?php

namespace Container9HJjwqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WQp8s5HService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.WQp8s5H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WQp8s5H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'thread' => ['privates', '.errored..service_locator.WQp8s5H.App\\Entity\\Thread', NULL, 'Cannot autowire service ".service_locator.WQp8s5H": it needs an instance of "App\\Entity\\Thread" but this type has been excluded in "config/services.yaml".'],
        ], [
            'thread' => 'App\\Entity\\Thread',
        ]);
    }
}
