<?php

namespace Container9HJjwqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Hydra_JsonSchema_SchemaFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.hydra.json_schema.schema_factory' shared service.
     *
     * @return \ApiPlatform\Hydra\JsonSchema\SchemaFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/JsonSchema/SchemaFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Hydra/JsonSchema/SchemaFactory.php';

        $a = ($container->privates['api_platform.hydra.json_schema.schema_factory.inner'] ?? $container->load('getApiPlatform_Hydra_JsonSchema_SchemaFactory_InnerService'));

        if (isset($container->privates['api_platform.hydra.json_schema.schema_factory'])) {
            return $container->privates['api_platform.hydra.json_schema.schema_factory'];
        }

        return $container->privates['api_platform.hydra.json_schema.schema_factory'] = new \ApiPlatform\Hydra\JsonSchema\SchemaFactory($a);
    }
}
