<?php

namespace Container9HJjwqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetMembersService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\GetMembers' shared autowired service.
     *
     * @return \App\Controller\GetMembers
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GetMembers.php';

        $container->services['App\\Controller\\GetMembers'] = $instance = new \App\Controller\GetMembers();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\GetMembers', $container));

        return $instance;
    }
}
