<?php

namespace Container9HJjwqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupRequestService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HWySRUk.App\Entity\GroupRequest' shared service.
     *
     * @return \App\Entity\GroupRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.HWySRUk": it needs an instance of "App\\Entity\\GroupRequest" but this type has been excluded in "config/services.yaml".');
    }
}
