<?php

namespace Container9HJjwqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJwtDecoratorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\OpenApi\JwtDecorator' shared autowired service.
     *
     * @return \App\OpenApi\JwtDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/OpenApi/Factory/OpenApiFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/OpenApi/JwtDecorator.php';

        return $container->privates['App\\OpenApi\\JwtDecorator'] = new \App\OpenApi\JwtDecorator(($container->privates['App\\OpenApi\\JwtDecorator.inner'] ?? $container->load('getJwtDecorator_InnerService')));
    }
}
