<?php

namespace Container9HJjwqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThreadService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WQp8s5H.App\Entity\Thread' shared service.
     *
     * @return \App\Entity\Thread
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WQp8s5H": it needs an instance of "App\\Entity\\Thread" but this type has been excluded in "config/services.yaml".');
    }
}
