<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9HJjwqM\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9HJjwqM/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container9HJjwqM.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container9HJjwqM\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container9HJjwqM\App_KernelTestDebugContainer([
    'container.build_hash' => '9HJjwqM',
    'container.build_id' => '275fe184',
    'container.build_time' => 1678967276,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9HJjwqM');
